### ISSUE TITLE
Update button not clickable

### ISSUE THREAD

**Issue by onetrev** [gblock0/resize-working-files#1]
I noticed in Brackets there is an update for your extension the but green update button is shaded out and not clickable. I've seen this before, not exactly sure why this happens but the fix I posted here work for this extension.

https://github.com/chuyik/brackets-snippets/issues/11

Hope that helps!

**Comment by gblock0** [comment]
Just pushed in v1.6.0 and updated the extension. Please let me know if that worked.

**Comment by gblock0** [comment]
Just tested on a friend's computer and it seems to work. Thanks!
